// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWHICjBQlSEKKnBfzxtF4a7xf1YmI8owU',
    appId: '1:805390076705:web:ed847c0808d8f371b8cc60',
    messagingSenderId: '805390076705',
    projectId: 'cmsc-23-b2l-bgsy',
    authDomain: 'cmsc-23-b2l-bgsy.firebaseapp.com',
    storageBucket: 'cmsc-23-b2l-bgsy.appspot.com',
    measurementId: 'G-S9X8C9HSYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8FE8HXEho22-s-8xla1z-OGjZBKes76A',
    appId: '1:805390076705:android:caf7f5308d675bd7b8cc60',
    messagingSenderId: '805390076705',
    projectId: 'cmsc-23-b2l-bgsy',
    storageBucket: 'cmsc-23-b2l-bgsy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5r6Pq4KcmXTZ5ZGF2WTVzmzGKNlKMQ8',
    appId: '1:805390076705:ios:344ff1b632666177b8cc60',
    messagingSenderId: '805390076705',
    projectId: 'cmsc-23-b2l-bgsy',
    storageBucket: 'cmsc-23-b2l-bgsy.appspot.com',
    iosClientId: '805390076705-soh2cb2elj9dj31rovn61kva3hul4dcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo5r6Pq4KcmXTZ5ZGF2WTVzmzGKNlKMQ8',
    appId: '1:805390076705:ios:344ff1b632666177b8cc60',
    messagingSenderId: '805390076705',
    projectId: 'cmsc-23-b2l-bgsy',
    storageBucket: 'cmsc-23-b2l-bgsy.appspot.com',
    iosClientId: '805390076705-soh2cb2elj9dj31rovn61kva3hul4dcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
